import '../styles/globals.css'
import Layout from '../components/layouts'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/okamon.png" />
      </Head>
      <Layout>
          <Component {...pageProps} />
      </Layout>
    </>
  )
}
